name: BubbleAnnounce
main: com.bubblecraft.bubbleannounce.BubbleAnnounce
version: 1.0.0
author: eirvi
description: Highly configurable announcement plugin for Bubblecraft
api-version: 1.21
commands:
  test:
    description: Triggers all announcements with permission
    usage: /test <Announce>
    permission: test.announce
    permission-message: "&cYou do not have permission to use this command."
  runannouncements:
    description: Runs all announcements (hidden from players)
    usage: /runannouncements
    permission: announce.run
    permission-message: "&cYou do not have permission to use this command."
  bubbleannounce:
    description: Admin command to manage BubbleAnnounce
    usage: /bubbleannounce reload
    permission: bubbleannounce.admin
    permission-message: "&cYou do not have permission to use this command."
